name: sound_chat
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player:
  #http: ^0.12.0+2
  http: ^0.13.0
  #flutter_radio:
  url_audio_stream: ^1.0.0+3
  url_launcher: ^5.7.10
  youtube_player_flutter: ^7.0.0+7
  #youtube_plyr_iframe: ^1.3.2+1
  toast: ^0.1.5
  provider: ^4.3.3
  cached_network_image: ^2.5.0
  photo_view: ^0.10.3
  flutter_media_notification: ^1.2.6
  flutter_launcher_icons: ^0.8.1
  meedu_player: ^0.4.3
  wakelock: ^0.2.1+1
  draggable_widget: ^1.1.1
  wc_form_validators: ^0.1.1
  webview_flutter: ^1.0.7
 # ext_video_player: ^0.0.4
  #shared_preferences: 0.5.8
  shared_preferences: ^2.0.5
  splashscreen: ^1.3.5
  font_awesome_flutter: ^8.11.0
  animated_text_kit: ^3.1.2
  back_button_interceptor: ^4.4.2
  carousel_slider: ^3.0.0
  flutter_braintree: ^1.1.0+1
  flutter_stripe_payment: ^0.0.12
  connectivity: ^3.0.2
  audioplayer: ^0.8.1
  #image_picker: ^0.7.4
  image_picker: ^0.6.6+1
  flutter_html: ^1.2.0
  whatsapp_unilink: ^1.0.0+1
  file_picker: ^1.4.3+2



    # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/soundpic.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:Montserrat-SemiBold.ttf

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
    - family: Montserrat1
      fonts:
         - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf

  assets:
    - assets/
    -  assets/soundbg.png
    - assets/profile.png
    - assets/soundchatbg.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
