name: sound_chat
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  url_launcher: ^6.0.0-nullsafety
  #youtube_player_flutter: ^8.0.0
  toast: ^0.1.5
  provider: ^6.0.1
  cached_network_image: ^3.1.0
  photo_view: ^0.13.0
  flutter_media_notification: ^1.2.6
  flutter_launcher_icons: ^0.9.2
  wakelock: ^0.5.6
  draggable_widget: ^2.0.0
  wc_form_validators: ^1.0.0
  webview_flutter: ^2.1.2
  shared_preferences: ^2.0.8
  splashscreen: ^1.3.5
  font_awesome_flutter: ^9.2.0
  animated_text_kit: ^4.2.1
  back_button_interceptor: ^5.0.2
  carousel_slider: ^4.0.0
  # flutter_braintree: ^2.0.0+1
  #flutter_stripe_payment: ^0.0.17
  connectivity: ^3.0.6
  # audioplayer: ^0.8.1
  image_picker: ^0.8.4+3
  flutter_html: ^2.1.5
  whatsapp_unilink: ^2.0.0
  # file_picker: ^4.1.3
  audioplayers: ^0.20.1
  shimmer: ^2.0.0
  firebase_core: ^1.8.0
  firebase_messaging: ^10.0.9
  firebase_auth: ^3.1.4
  cloud_firestore: ^2.5.4
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  google_sign_in: ^5.2.0
  cupertino_icons: ^1.0.3
  curved_navigation_bar: ^1.0.1
  awesome_dialog: ^2.1.1
  # flutter_advanced_drawer: ^1.2.3+1
  badges: ^2.0.1
  vibration: ^1.7.3
  better_player: ^0.0.77
  stripe_payment: ^1.1.4
  youtube_player_iframe: ^2.2.2
  flutter_colorpicker: ^0.6.1
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_512.png"

flutter:

  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
       
        
    - family: Montserrat1
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf

  assets:
    - assets/