name: sound_chat
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player:
  #http: ^0.12.0+2
  http: ^0.13.3
  #flutter_radio:
  #  url_audio_stream: ^1.0.0+3
  url_launcher: ^5.7.10
  youtube_player_flutter: ^8.0.0
  #youtube_plyr_iframe: ^1.3.2+1
  toast: ^0.1.5
  provider: ^4.3.3
  cached_network_image: ^3.0.0
  photo_view: ^0.10.3
  flutter_media_notification: ^1.2.6
  flutter_launcher_icons: ^0.9.0
  meedu_player: ^0.4.3
  wakelock: ^0.2.1+1
  draggable_widget: ^1.1.1
  wc_form_validators: ^0.1.1
  webview_flutter: ^1.0.7
  # ext_video_player: ^0.0.4
  #shared_preferences: 0.5.8
  shared_preferences: ^2.0.5
  splashscreen: ^1.3.5
  font_awesome_flutter: ^8.11.0
  animated_text_kit: ^3.1.2
  back_button_interceptor: ^4.4.2

  carousel_slider: ^3.0.0
  flutter_braintree: ^1.1.0+1
  flutter_stripe_payment: ^0.0.12
  connectivity: ^3.0.2
  audioplayer: ^0.8.1
  image_picker: ^0.7.4
  #image_picker: ^0.6.6+1
  flutter_html: ^1.2.0
  whatsapp_unilink: ^1.0.0+1
  file_picker: ^1.4.3+2
  audioplayers: ^0.18.3
  shimmer: ^2.0.0
  firebase_core:
  firebase_messaging:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/soundpic.png"

flutter:

  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
    - family: Montserrat1
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf

  assets:
    - assets/
    -  assets/soundbg.png
    - assets/profile.png
    - assets/soundchatbg.png
