name: sound_chat
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player:
  http: ^0.13.3
  url_launcher: ^6.0.0-nullsafety
  youtube_player_flutter: ^8.0.0
  toast: ^0.1.5
  provider: ^5.0.0
  cached_network_image: ^3.1.0
  photo_view: ^0.12.0
  flutter_media_notification: ^1.2.6
  flutter_launcher_icons: ^0.9.2
  wakelock: ^0.5.3+3
  draggable_widget: ^2.0.0
  wc_form_validators: ^1.0.0
  webview_flutter: ^2.0.12
  shared_preferences: ^2.0.7
  splashscreen: ^1.3.5
  font_awesome_flutter: ^9.1.0
  animated_text_kit: ^4.2.1
  back_button_interceptor: ^5.0.1
  carousel_slider: ^4.0.0
  flutter_braintree: ^2.0.0+1
  flutter_stripe_payment: ^0.0.14
  connectivity: ^3.0.6
  audioplayer: ^0.8.1
  image_picker: ^0.8.4
  flutter_html: ^2.1.2
  whatsapp_unilink: ^2.0.0
  file_picker: ^4.0.1
  audioplayers: ^0.19.1
  shimmer: ^2.0.0
  firebase_core:
  firebase_messaging: ^10.0.6
  firebase_auth: ^3.1.0
  cloud_firestore: ^2.5.1
  socket_io_client: ^1.0.1
  google_sign_in:
  cupertino_icons: ^1.0.3
  curved_navigation_bar: ^1.0.1
  awesome_dialog: ^2.1.1
  flutter_advanced_drawer: ^1.2.3
  badges: ^2.0.1
  vibration: ^1.7.3
  chewie: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/soundpic.png"

flutter:

  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
    - family: Montserrat1
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf

  assets:
    - assets/
    -  assets/soundbg.png
    - assets/profile.png
    - assets/soundchatbg.png
